### ISSUE TITLE
 J2V8 native library not loaded

### ISSUE THREAD

**Issue by SpreeHertz** [customrealms/core#30]
I compiled the plugin using `npm run build:jar`, uploaded it to my Minecraft server, but there was an error in the console:

```cmd
[ERROR] .... [org.bukkit.craftbukkit.v1_18_R2.CraftServer] J2V8 native library not loaded initializing cordhelper v0.1.0 (Is it up to date?)

java.lang.IllegalStateException: J2V8 native library not loaded

at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:195) ~[cordhelper.jar:?]

at com.eclipsesource.v8.V8.createV8Runtime(V8.java:149) ~[cordhelper.jar:?]

at com.eclipsesource.v8.V8.createV8Runtime(V8.java:125) ~[cordhelper.jar:?]

at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:58) ~[cordhelper.jar:?]

at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:45) ~[cordhelper.jar:?]

at io.customrealms.runtime.Runtime.<init>(Runtime.java:51) ~[cordhelper.jar:?]

at io.customrealms.jsplugin.JsPlugin.setup(JsPlugin.java:39) ~[cordhelper.jar:?]

at io.customrealms.jsplugin.JsPlugin.<init>(JsPlugin.java:29) ~[cordhelper.jar:?]

at io.customrealms.MainPlugin.onLoad(MainPlugin.java:30) ~[cordhelper.jar:?]

at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.18.2.jar:git-Paper-283]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-283]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-283]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:

no j2v8_linux_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:75) ~[cordhelper.jar:?]

at com.eclipsesource.v8.V8.load(V8.java:71) ~[cordhelper.jar:?]

at com.eclipsesource.v8.V8.createV8Runtime(V8.java:145) ~[cordhelper.jar:?]
```

How do I fix this?

**Comment by Frontesque** [comment]
From my experience, it is running because you compiled the plugin on a different version of java than the server. 

I compiled on my server rather than my computer and it worked fine
